#!/usr/bin/env bash
# -*- mode: bash-ts; -*- vim:ft=bash

read -r -d '' BEMENU_OPTS << EOF
 --fn "monospace 14"
 --wrap
 --list "10 down"
 --prompt "run:"
 --prefix ">"
 --ignorecase
 --no-cursor
 --fork
 --fixed-height
 --single-instance
 --scrollbar "none"
 --monitor "focused"
 --no-overlap
 --center
 --width-factor 0.3
 --border "2"
 --border-radius "4"
 --bdr "#80B0E0"
 --tf "#76C5A4"
 --tb "#1A1D27"
 --nf "#D7D7D7"
 --nb "#1A1D27"
 --af "#D7D7D7"
 --ab "#1A1D27"
 --ff "#ECECEC"
 --fb "#1A1D27"
 --sf "#1A1D27"
 --sb "#76C5A4"
 --hf "#1A1D27"
 --hb "#76C5A4"
EOF

export BEMENU_OPTS;
exec bemenu-run "$@";