#!/bin/fish

set -l appname $argv[1]

if test -z $appname
    printf 'expected argument, found "%s"\n' $appname
    exit 1
end

switch $appname
    case terminal
        $TERMINAL $argv[2] > /dev/null 2>&1 & disown
    case editor
        $EDITOR > /dev/null 2>&1 & disown
    case browser
        $BROWSER $argv[2] > /dev/null 2>&1 & disown
    case launcher
        $LAUNCHER $argv[2] > /dev/null 2>&1 & disown
    case filemanager
        $FILEMANAGER $argv[2] > /dev/null 2>&1 & disown
    case mediaplayer
        $MEDIAPLAYER $argv[2] > /dev/null 2>&1 & disown
    case imageviewer
        $IMAGEVIEWER $argv[2] > /dev/null 2>&1 & disown
    case '*'
        echo 'option invalid.'
        exit 1
end
