#!/bin/sh

case $1 in
    1)
    hyprctl dispatch workspace 1
    eww update hypr-active=1
    ;;
    2)
    hyprctl dispatch workspace 2
    eww update hypr-active=2
    ;;
    3)
    hyprctl dispatch workspace 3
    eww update hypr-active=3
    ;;
    4)
    hyprctl dispatch workspace 4
    eww update hypr-active=4
    ;;
    5)
    hyprctl dispatch workspace 5
    eww update hypr-active=5
    ;;
    6)
    hyprctl dispatch workspace 6
    eww update hypr-active=6
    ;;
    7)
    hyprctl dispatch workspace 7
    eww update hypr-active=7
    ;;
    8)
    hyprctl dispatch workspace 8
    eww update hypr-active=8
    ;;
    9)
    hyprctl dispatch workspace 9
    eww update hypr-active=9
    ;;
    *)
    exit;;
esac
