#!/bin/env perl

use strict;
use warnings;

my $confirm = `yad --timeout=10 --timeout-indicator=top --text-align=center --text='Are you sure you want to log out?' --fixed --title='Confirm Log Out' --buttons-layout=center && printf 'true'`;

if ($confirm eq 'true')
{
    my $check = `yad --timeout=3 --text='logging out in 3 seconds' --no-buttons --timeout-indicator=top --fixed --text-align=center --fixed`;
    system "loginctl kill-user $ENV{'USER'}";
}

exit 0;