#!/bin/sh

# this script is for sending a window to tag [1-9] in the river
# wayland compositor

[ -n "$1" ] || exit

case "$1" in
    1)
    riverctl set-view-tags 1
    ;;
    2)
    riverctl set-view-tags 2
    ;;
    3)
    riverctl set-view-tags 4
    ;;
    4)
    riverctl set-view-tags 8
    ;;
    5)
    riverctl set-view-tags 16
    ;;
    6)
    riverctl set-view-tags 32
    ;;
    7)
    riverctl set-view-tags 64
    ;;
    8)
    riverctl set-view-tags 128
    ;;
    9)
    riverctl set-view-tags 256
    ;;
    *)
    printf 'invalid argument\n'
    exit
    ;;
esac