#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;

GetOptions(
    "up|u"   => \my $up,
    "down|d" => \my $down,
    "mute|m" => \my $mute,
    "help|h" => \my $help
) or die "Invalid command given to $0, see --help for usage information";

if ($up) {

  system "pamixer -i 5";

} elsif ($down) {

  system "pamixer -d 5";

} elsif ($mute) {

  system "pamixer -t";

} elsif ($help) {

  print "\x1B[1;3mvol\x1B[0m - USAGE:\n\n\t--up/-u\t\tIncrease volume by 5%\n\t--down/-d\tDecrease volume by 5%\n\t--mute/-m\tMute/Unmute volume\n\n";

} else {

  print "\x1B[1;3mvol\x1B[0m - USAGE:\n\n\t--up/-u\t\tIncrease volume by 5%\n\t--down/-d\tDecrease volume by 5%\n\t--mute/-m\tMute/Unmute volume\n\n";

}